### ISSUE TITLE
Description of Project

### ISSUE THREAD

**Issue by danigalindo10** [danigalindo10/tv-shows#21]
### Kanban Set Up
For this project, we have 2 team members: @Eternalgratis and @danigalindo10 

[This is the link to the project](https://github.com/danigalindo10/tv-shows/projects/1)

**Comment by hiromataba** [comment]
Hi @danigalindo10 and @Eternalgratis     :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  
- Profesional README file :rocket: 

## Required Changes ♻️

- [x] The link of the project you should provide is from the kanban board, not the project, this is the link you should add 👇 

https://github.com/danigalindo10/tv-shows/projects/1

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Eternalgratis** [comment]
### Kanban Set Up
For this project, we have 2 team members: @Eternalgratis and @danigalindo10 

[This is the link to the project](https://github.com/danigalindo10/tv-shows/projects/1)

**Comment by Nemwel-Boniface** [comment]
## Hello @Eternalgratis  and @danigalindo10              :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the requested changes and for setting your Kanban board correctly good job! :partying_face: All the best in your Project :sunglasses:  
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by danigalindo10** [comment]
Hello @Nemwel-Boniface,
Thank you so much for your feedback. Have a nice week.
